---
- name: Configure sudo users with SSH keys and require password change on first login
  hosts: all
  become: true
  vars:
    users:
      - username: manhal
        ssh_keys:
             - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3/HS3lfaghgC/I2HzZMasK9qaMpgJ0AqwCJd4iABUhluW7fJ6dFZMZZ1twSp2eqDvWmgKWuuK7DI678RCw0LbREM0Ufgm/H3Ak83UnjxdVjWZwZucBaAmr83abneYODsx7cgNwCbx4bsAAFIli/N0THVPYmNQ3qf8Jxzh/DUklzj1CtoTbpf+6hy29MdgmBpGUWMEoWLQ+QRnvD7KROPKXLC5dyxtL9N5LyvE+ybJqmA6iXe7p9wzX+HU0RFxAC8oUOd/fgVLNTFr7/IeSZ2hSxZ9Il0P8FG7nLKRwB7DfaIEcqKXeav9qFunMMo7nsTxS/9rfn6ZER8n2Pn7fstr Manhal@BB-SimSim"
        email: "manhal@afrinic.net"
    users_to_remove:
      - hanshala
      - daniel
      - siraj
      - samir

  tasks:
    - name: Install required packages
      package:
        name:
          - sudo
          - openssh-server
          - "{{ 'mailutils' if ansible_facts['os_family'] == 'Debian' else 'mailx' }}"
        state: latest
      register: package_install
      retries: 3
      delay: 5
      until: package_install is success

    - name: Check if users exist and set fact for new users
      command: "getent passwd {{ item.username }}"
      register: user_check
      loop: "{{ users }}"
      changed_when: false
      failed_when: false

    - name: Initialize user_passwords dictionary
      set_fact:
        user_passwords: {}

    - name: Generate passwords for new users
      set_fact:
        user_passwords: "{{ user_passwords | combine({item.item.username: lookup('password', '/dev/null length=15 chars=ascii_letters+digits')}) }}"
      loop: "{{ user_check.results }}"
      when: item.rc != 0

    - name: Create new users with plain-text passwords if they do not exist
      user:
        name: "{{ item.username }}"
        password: "{{ user_passwords[item.username] | default('') | password_hash('sha512') }}"
        groups: sudo
        append: yes
        create_home: yes
        shell: /bin/bash
        update_password: on_create
        expires: -1
      loop: "{{ users }}"
      when: user_passwords[item.username] is defined
      register: user_creation
      failed_when: user_creation is failed

    - name: Set password to expire upon first login for newly created users
      command: chage -d 0 "{{ item.username }}"
      loop: "{{ users }}"
      when: user_passwords[item.username] is defined
      register: chage_result
      failed_when: chage_result is failed

    - name: Update existing users
      user:
        name: "{{ item.username }}"
        groups: sudo
        append: yes
      loop: "{{ users }}"
      when: user_passwords[item.username] is not defined
      register: user_update
      failed_when: user_update is failed

    - name: Deploy SSH public keys for the users
      authorized_key:
        user: "{{ item.0.username }}"
        state: present
        key: "{{ item.1 }}"
      loop: "{{ users | subelements('ssh_keys') }}"
      register: ssh_key_deploy
      failed_when: ssh_key_deploy is failed

    - name: Send password to users via email
      mail:
        host: relay.afrinic.net
        port: 25
        to: "{{ item.email }}"
        subject: "Your new account password"
        body: |
          Dear {{ item.username }},
          Your new account has been created on the following host: {{ ansible_host }}.
          Username: {{ item.username }}
          Password: {{ user_passwords[item.username] }}
          Please change your password upon first login.
          **Note:** This is an automated message generated by Ansible. Please do not reply to this email.
          Best regards,
          Infra Team
        from: wororoook@inx.net.za
      loop: "{{ users }}"
      when: user_passwords[item.username] is defined
      register: email_result
      failed_when: email_result is failed
      ignore_errors: yes

    - name: Remove specified users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ users_to_remove }}"
      register: user_removal
      failed_when: user_removal is failed

